<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="gigla" name="com.thecalculatorsite.test.cucumber.CalculatorFeatureTest" tests="3" failures="0" timestamp="11 мар 2018 23:10:08 GMT" time="47.763" errors="1">
  <testcase name="feature" time="21.847" classname="com.thecalculatorsite.test.cucumber.CalculatorFeatureTest"/>
  <testcase name="feature" time="10.273" classname="com.thecalculatorsite.test.cucumber.CalculatorFeatureTest"/>
  <testcase name="feature" time="15.643" classname="com.thecalculatorsite.test.cucumber.CalculatorFeatureTest">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [$12.13] but found [dollar12.13]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [$12.13] but found [dollar12.13]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.thecalculatorsite.test.cucumber.CalculatorFeatureTest.feature(CalculatorFeatureTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.thecalculatorsite.framework.core.runner.Runner.run(Runner.java:53)
at com.thecalculatorsite.framework.core.runner.Runner.main(Runner.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: expected [$12.13] but found [dollar12.13]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.thecalculatorsite.stepdefs.CalculatorPageSteps.lambda$loanPayoffCalculationResultIs$2(CalculatorPageSteps.java:179)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
at com.thecalculatorsite.stepdefs.CalculatorPageSteps.loanPayoffCalculationResultIs(CalculatorPageSteps.java:178)
at ✽.And loan payoff calculation result is:(loan.payoff.calc/loanPayoffCalculator.feature:65)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.thecalculatorsite.test.cucumber.CalculatorFeatureTest -->
